apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8s-diagnosis-agent.fullname" . }}-config
  labels:
    {{- include "k8s-diagnosis-agent.labels" . | nindent 4 }}
data:
  config.yaml: |
    llm:
      default_model: {{ .Values.config.llm.defaultModel | quote }}
      temperature: {{ .Values.config.llm.temperature }}
      max_tokens: {{ .Values.config.llm.maxTokens }}
      timeout: {{ .Values.config.llm.timeout }}
    
    web:
      host: {{ .Values.config.web.host | quote }}
      port: {{ .Values.config.web.port }}
      debug: {{ .Values.config.web.debug }}
      cors_origins: {{ .Values.config.web.corsOrigins | toJson }}
    
    logging:
      level: {{ .Values.config.logging.level | quote }}
      format: {{ .Values.config.logging.format | quote }}
    
    session:
      timeout: {{ .Values.config.session.timeout }}
      max_conversation_length: {{ .Values.config.session.maxConversationLength }}
    
    permissions:
      enabled: {{ .Values.config.permissions.enabled }}
      default_role: {{ .Values.config.permissions.defaultRole | quote }}
      roles: {{ .Values.config.permissions.roles | toJson }}
    
    {{- if .Values.multiCluster.enabled }}
    multi_cluster:
      enabled: true
      clusters:
        {{- range .Values.multiCluster.clusters }}
        - name: {{ .name | quote }}
          kubeconfig_path: "/app/kubeconfig/{{ .name }}.yaml"
        {{- end }}
    {{- end }}

---
{{- if .Values.configMap.kubeconfig.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8s-diagnosis-agent.fullname" . }}-kubeconfig
  labels:
    {{- include "k8s-diagnosis-agent.labels" . | nindent 4 }}
data:
  {{- if .Values.configMap.kubeconfig.data }}
  default.yaml: |
    {{- .Values.configMap.kubeconfig.data | nindent 4 }}
  {{- end }}
  {{- if .Values.multiCluster.enabled }}
  {{- range .Values.multiCluster.clusters }}
  {{ .name }}.yaml: |
    {{- .kubeconfig | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end }} 