{{- if or .Values.secrets.llmApiKeys.openai .Values.secrets.llmApiKeys.claude .Values.secrets.llmApiKeys.deepseek }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8s-diagnosis-agent.fullname" . }}-secrets
  labels:
    {{- include "k8s-diagnosis-agent.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.llmApiKeys.openai }}
  openai-api-key: {{ .Values.secrets.llmApiKeys.openai | b64enc }}
  {{- end }}
  {{- if .Values.secrets.llmApiKeys.claude }}
  claude-api-key: {{ .Values.secrets.llmApiKeys.claude | b64enc }}
  {{- end }}
  {{- if .Values.secrets.llmApiKeys.deepseek }}
  deepseek-api-key: {{ .Values.secrets.llmApiKeys.deepseek | b64enc }}
  {{- end }}
---
{{- end }} 